const localization: { [key: string]: string } = {
  'gregtech:gt.blockmachines:10951': 'Elite Mass Fabricator II (ZPM)',
  'gregtech:gt.metaitem.01:32464': 'Heavy Duty Alloy Ingot T3',
  'gregtech:gt.blockmachines:1186': 'Advanced Circuit Assembler VI (ZPM)',
  'gregtech:gt.blockmachines:214': 'Advanced Assembling Machine III (EV)',
  'minecraft:end_stone:0': 'End Stone',
  'gregtech:gt.metaitem.02:30500': 'Exquisite Diamond',
  'gregtech:gt.blockmachines:1182': 'Advanced Circuit Assembler II (HV)',
  'gregtech:gt.metaitem.01:32672': 'Field Generator (HV)',
  'gregtech:gt.metaitem.03:32094': 'Wetware Supercomputer (UV)',
  'gregtech:gt.metaitem.01:24347': 'Firestone Lens',
  'gregtech:gt.metaitem.01:32692': 'Sensor (HV)',
  'gregtech:gt.metaitem.01:32680': 'Emitter (LV)',
  'minecraft:nether_star:0': 'Nether Star',
  'Thaumcraft:ItemSanitySoap:0': 'Sanitizing Soup',
  'gregtech:gt.blockmachines:10990': 'Elite Recycler (LuV)',
  'gregtech:gt.metaitem.03:32091': 'Crystalprocessor Mainframe (UV)',
  'gregtech:gt.metaitem.01:32690': 'Sensor (LV)',
  'harvestcraft:cheeseItem:0': 'Cheese',
  'minecraft:fish:3': 'Pufferfish',
  'gregtech:gt.blockmachines:463': 'Advanced Mass Fabricator II (HV)',
  'gregtech:gt.metaitem.01:32682': 'Emitter (HV)',
  'gregtech:gt.blockmachines:482': 'Advanced Replicator (MV)',
  'gregtech:gt.metaitem.01:32670': 'Field Generator (LV)',
  'gregtech:gt.blockmachines:465': 'Advanced Mass Fabricator IV (IV)',
  'minecraft:melon_block:0': 'Melon',
  'minecraft:soul_sand:0': 'Soul Sand',
  'gregtech:gt.metaitem.01:32674': 'Field Generator (IV)',
  'minecraft:tnt:0': 'TNT',
  'gregtech:gt.blockmachines:345': 'Advanced Scanner IV (IV)',
  'gregtech:gt.metaitem.01:32462': 'Heavy Duty Alloy Ingot T1',
  'gregtech:gt.metaitem.01:32463': 'Heavy Duty Alloy Ingot T2',
  'GalacticraftMars:item.itemBasicAsteroids:0': 'Heavy Duty Plate (T3)',
  'dreamcraft:item.HeavyDutyPlateTier4:0': 'Heavy Duty Plate Tier 4',
  'dreamcraft:item.HeavyDutyPlateTier5:0': 'Heavy Duty Plate Tier 5',
  'dreamcraft:item.HeavyDutyPlateTier6:0': 'Heavy Duty Plate Tier 6',
  'dreamcraft:item.HeavyDutyPlateTier7:0': 'Heavy Duty Plate Tier 7',
  'dreamcraft:item.HeavyDutyPlateTier8:0': 'Heavy Duty Plate Tier 8',
  'gregtech:gt.blockmachines:12526': 'Advanced Crop Synthesiser VII (UV)',

  'gregtech:gt.metaitem.01:32675': 'Field Generator (LuV)',
  'gregtech:gt.metaitem.01:32684': 'Emitter (IV)',
  'gregtech:gt.metaitem.01:32671': 'Field Generator (MV)',
};

export const localize = (unlocalizedName: string) => {
  console.log(unlocalizedName.replaceAll(':', '--'), '                 ');
  return localization[unlocalizedName] ?? unlocalizedName;
};